import java.io.*;
import java.util.*;

public class Main {
	public static void main(String[] args) throws Exception {
		BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
		Map<String, Integer> m = new HashMap<String, Integer>();
		StringTokenizer st = new StringTokenizer("a b c");
		for (int i = 0; i < 10; i++) {
			if (st.hasMoreTokens()) {
				System.out.println(st.nextToken());
			}
			else
			{
				System.out.println("no token!");
				break;
			}
		}
		m.put("TOMANDTOMSONCOPERATIONHARDWORKSYSTEMHELLOWORLDWEARETHRFRIENDWHOAREYOUJUMMYWEARELONGTOSEEYOUAGAINCOMMONWECANFLYHOWDYWAWAWAWAWAWAWAWWEMUSTBEARICHWEARETHEFRIENDSWEAREVERYVERYVERYVERYVERYVERYVERYVERYVERYRICH", 1);
		System.out.println(m.containsKey("JAY"));
		System.out.println(m.containsKey("TOMANDTOMSONCOPERATIONHARDWORKSYSTEMHELLOWORLDWEARETHRFRIENDWHOAREYOUJUMMYWEARELONGTOSEEYOUAGAINCOMMONWECANFLYHOWDYWAWAWAWAWAWAWAWWEMUSTBEARICHWEARETHEFRIENDSWEAREVERYVERYVERYVERYVERYVERYVERYVERYVERYRICH"));
		System.out.println(m.get("TOMANDTOMSONCOPERATIONHARDWORKSYSTEMHELLOWORLDWEARETHRFRIENDWHOAREYOUJUMMYWEARELONGTOSEEYOUAGAINCOMMONWECANFLYHOWDYWAWAWAWAWAWAWAWWEMUSTBEARICHWEARETHEFRIENDSWEAREVERYVERYVERYVERYVERYVERYVERYVERYVERYRICH"));
	}
}


